---
name: Update blog posts workflow
on:
    schedule:
        - cron: 0 0,12 * * *
    workflow_dispatch: null
jobs:
    update-readme-with-blog-posts:
        name: Update README with the latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: gautamkrishnar/blog-post-workflow@v1
              with:
                  commit_message: Automatically update README with the latest blog post
                  feed_list: https://jerrynsh.com/rss/
                  max_post_count: 5
                  template: <tr><td><a href="$url">$title</a></td><td>$date</td></tr>
