name: Update blog posts workflow
on:
    schedule:
        # Runs at minute 0 past hour 0 and 12
        - cron: "0 0,12 * * *"
    workflow_dispatch:

jobs:
    update-readme-with-blog-posts:
        name: Update README with the latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                  feed_list: "https://jerrynsh.com/rss/"
                  commit_message: "✍️ Automatically update README with the latest blog post"
