name: Update Medium posts workflow
on:
    schedule:
        # Runs at minute 0 past hour 0 and 12
        - cron: "0 0,12 * * *"
    workflow_dispatch:

jobs:
    update-readme-with-medium-posts:
        name: Update Jerry's README with his latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                  feed_list: "https://dev.to/feed/jerrynsh"
                  commit_message: "🤖 Automatically update README with latest blog post"
                  filter_comments: ""
