name: Update GitHub activity workflow
on:
    schedule:
        # Runs every hour at minute 0
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    update-readme-with-github-activity:
        name: Update README with the latest GitHub activities
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jamesgeorge007/github-activity-readme@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  COMMIT_MSG: "🦾 Automatically update README with the latest GitHub activities"
