name: Update Todoist activity workflow
on:
    schedule:
        # Runs every hour at minute 0
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    update-readme-with-todoist-activity:
        name: Update README with the latest Todoist activities
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: abhisheknaiidu/todoist-readme@master
              with:
                  TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
                  PREMIUM: ""
